-- ============================================================
-- ACME SCHOOL - Secuencias
-- Ejecutar como: acme_school
-- ============================================================

ALTER SESSION SET CURRENT_SCHEMA = acme_school;

CREATE SEQUENCE seq_estudiante START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_docente START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_curso START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_periodo START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_seccion START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_inscripcion START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_nota START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_auditoria START WITH 1 INCREMENT BY 1 NOCACHE;
